### PR TITLE
Add support for overlay triplets

### PR DESCRIPTION
**Pull request by pkgw**
This helps with #4.

I also silenced a warning as a conservative way to make it go away — it refers to a field in a Serde struct so if we just get rid of it, that could conceivably break existing files.

Finally I also grouped the return values from the `process_metadata()` function into a struct since the tuple was getting unwieldy.

### CODE REVIEW

**Comment by pkgw** [comment]
@waych Hmm, should there be CI running with the GitHub Workflows here?

**Review by kornelski — APPROVED** [review]

**Comment by pkgw** [comment]
I should mention that the only ways to test the functionality that I could think of were either (1) trivial "does Serde work?" or (2) would require a whole new stack to actually run vcpkg. So I didn't add any tests :-/

**Comment by waych** [comment]
This looks pretty slick.

The Actions were all disabled.  I was able to re-enable them, but I think it will require a change to this PR to trigger them here.  I just kicked them off on the master branch; I have no idea yet if they still pass. 🤞

**Comment by pkgw** [comment]
Thanks! I've merged it in here to verify that the CI clears.

**Comment by pkgw** [comment]
Thanks! Would you mind looking into whether the [release checklist][1] still works?

[1]: https://github.com/mcgoo/cargo-vcpkg/blob/master/notes.md#making-a-release

**Pull request merged**
